services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'slaptai'
      MYSQL_ROOT_PASSWORD: 'verysecretpassword'
    ports:
      - 3307:3306
    expose:
      - 3307
